name: Sync

on:
  workflow_dispatch:
    # inputs:
    #   repo:
    #     type: string
    #     description: 'Target repo'
    #     required: false
    #     default: ''
  schedule:
    - cron: '38 */1 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          # owner: ${{ github.repository_owner }}
          owner: external-mirrors

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Sync
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # set -x

          sudo mkdir /mnt/sync
          sudo chown runner:runner -R /mnt/sync

          # git config user.name "github-actions[bot]"
          # git config user.email "github-actions[bot]@users.noreply.github.com"

          cp repos.json /mnt/sync/repos.json
          cd /mnt/sync
          jq -c '.[]' repos.json | while read -r config; do
            url=$(echo "$config" | jq -r '.url')
            type=$(echo "$config" | jq -r '.type')
            repo=$(echo "$config" | jq -r '.repo')
            first="0"

            echo "target: $repo"

            mkdir "$repo" && cd "$repo"

            echo "[$repo] Check if the mirror repository is created"
            set +e
            gh repo view "external-mirrors/$repo" > /dev/null
            ret="$?"
            set -e
            if [ "$ret" -ne 0 ]; then
              echo "[$repo] Creating target repo"
              gh repo create "external-mirrors/$repo" --homepage "$url" --disable-issues --disable-wiki --public
              first="1"
            fi

            echo "[$repo] Compare remotes"
            git ls-remote --quiet --heads --tags --refs "$url" > remote-src
            git ls-remote --quiet --heads --tags --refs "https://github.com/external-mirrors/$repo" > remote-dist
            set +e
            diff remote-src remote-dist > /dev/null
            ret="$?"
            set -e
            if [ "$ret" -eq 0 ]; then
              echo "[$repo] Mirror is synchronized. skip"
              cd /mnt/sync
              continue
            fi

            echo "[$repo] Cloning source repo"
            mkdir repo-dir && cd repo-dir
            git init --bare
            git remote add --mirror=fetch origin "$url"
            git config unset --all remote.origin.fetch
            git config set --append remote.origin.fetch '+refs/heads/*:refs/heads/*'
            git config set --append remote.origin.fetch '+refs/tags/*:refs/tags/*'
            gh repo edit {owner}/{repo} --default-branch "refs/heads/$( git remote show origin | grep "^  HEAD branch: " | cut -c 16- )"
            git remote set-url --push origin "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/external-mirrors/$repo"
            if [ "$first" -eq 0 ]; then
              git fetch --filter=blob:none
            else
              git fetch
            fi
            echo "[$repo] Pushing to mirror repo"
            git push --mirror origin
            cd ..
            echo "[$repo] Cleaning"
            rm -rf repo-dir remote-src remote-dist
            cd ..
          done
